article/urls.py
from django.contrib import admin
from django.urls import path

app_name = "article"


from .views import *
urlpatterns = [
    path('add_article/',add_article,name = "add_article"),
    path('detail/<int:id>/',detail,name="detail"),
    path('update/<int:id>/',update_article,name="update_article"),
    path('delete/<int:id>/',delete_article,name="delete_article"),
    path('add_comment/<int:id>/',add_comment,name="add_comment"),

]

myblog_2/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from article.views import dashboard
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('create_about/',views.create_about,name ="create_about"),
    path('about/',views.about,name ="about"),
    path('siyaset-yazi/',views.siyaset_yazi,name = "siyaset-yazi"),
    path('siyaset-haber/',views.siyaset_haber,name = "siyaset-haber"),
    path('articles/',include("article.urls")),
    path('user/',include('user.urls')),
    path('dashboard/',dashboard,name="dashboard"),
    path('spor-yazi/',views.spor_yazi,name = "spor-yazi"),
    path('spor-yazilar/',views.spor_haber,name = "spor_haber"),
    path('müzik/',views.muzik,name = "muzik"),
    path('sinema/',views.sinema,name = "sinema"),
    path('edebiyat/',views.edebiyat,name = "edebiyat"),
    path('sahne-sanatlari/',views.sahne,name = "sahne_sanatlari"),
    path('gorsel-sanatlar/',views.gorsel,name = "gorsel"),
    path('gezi-notu/',views.gezi,name = "gezi"),
    path('ceviri/',views.ceviri,name = "ceviri"),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.contrib.auth.models import Permission
from django.urls import path,include

app_name = "user"
Permission
from .views import *
urlpatterns = [
    path('register/',register,name="register"),
    path('login/',loginusr,name="login"),
    path('logout/',logoutusr,name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

ARTICLE_CATEGORY = (
    ("Siyaset-Yazı", "Siyaset-Yazı"),
    ("Siyaset-Haber", "Siyaset-Haber"),
    ("Spor-Yazı", "Spor-Yazı"),
    ("Spor-Haber", "Spor-Haber"),
    ("Müzik", "Müzik"),
    ("Sinema", "Sinema"),
    ("Edebiyat", "Edebiyat"),
    ("Sahne Sanatları", "Sahne Sanatları"),
    ("Görsel Sanatlar", "Görsel Sanatlar"),
    ("Gezi Notu", "Gezi Notu"),
    ("Çeviri", "Çeviri"),
)



class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete= models.CASCADE,verbose_name="Author")
    title = models.CharField(max_length= 50,verbose_name="Başlık")
    content = RichTextField(verbose_name = "İçerik")
    created_date = models.DateTimeField(auto_now_add= True,verbose_name="Creadet Date")
    article_image = models.FileField(blank=True,null=True,verbose_name="Makale Fotoğrafı")
    article_category = models.CharField(
        max_length=20,
        choices=ARTICLE_CATEGORY,
        default="Siyaset-Yazı",
        verbose_name="Makale Türü"
    )
    is_superarticle = models.BooleanField(verbose_name="Haftanın İçeriği Yap",default=0)
    def __str__(self):
     return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model): 
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="article" ,related_name="comments")
    comment_author = models.CharField(max_length= 50 ,verbose_name="c_author")
    comment_content = models.CharField(max_length=200,verbose_name="c_content")
    comment_date = models.DateTimeField(auto_now_add=True,verbose_name="comment_date")
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

class About(models.Model):
    author = models.ForeignKey("auth.User", on_delete= models.CASCADE,verbose_name="Author",default=None)
    content = RichTextField(verbose_name = "İçerik")

article/forms.py
from django import forms
from .models import About, Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image","article_category","is_superarticle"]

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = ["content"]

article/views.py
from django.db.models.query import RawQuerySet
from django.http import response
from django.shortcuts import redirect, render, HttpResponse,get_object_or_404
from django.urls import reverse
from .forms import ArticleForm, AboutForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import About, Article, Comment

# Create your views here.

def index(request):
    superarticles = Article.objects.filter(is_superarticle = 1)
    
    last_articles_query = Article.objects.all()
    last_articles = list()
    if len(last_articles_query)<6:
        for i in range(len(last_articles_query)):
            last_articles.append(last_articles_query[i])
    else:
        for i in range(6):
            last_articles.append(last_articles_query[i])

    return render(request,"index.html",{"s_articles":superarticles,"last_articles":last_articles})

def create_about(request):
    about = get_object_or_404(About)
    form = AboutForm(request.POST or None,instance=about)

    if form.is_valid():
        about_content = form.save(commit=False)
        about_content.author = request.user
        about_content.save()
        messages.success(request,"Hakkımızda Sayfası Başarıyla Güncellendi!")
        return redirect("dashboard")

    context = {
        "form" : form
    }
    return render(request,"create_about.html",context)

def about(request):
    abt = get_object_or_404(About,id=1)
    return render(request,"about.html",{"abt":abt})


def detail(request,id):
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    return render(request, "detail.html",{"article" : article, "comments" : comments})

@staff_member_required()
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles" : articles
    }
    return render(request,"dashboard.html",context)

@staff_member_required()
def add_article(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    superarticles = Article.objects.filter(is_superarticle = 1)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        if len(superarticles)>=2 and article.is_superarticle:
            article.is_superarticle = 0
            article.save()
            messages.warning(request,"Makale Başarıyla Eklendi. Fakat En Fazla 2 Tane Haftanın İçeriği Olabileceği İçin Haftanın İçeriklerine Eklenemedi.")
            return redirect("dashboard")

        article.save()
        messages.success(request,"Makale Başarıyla Eklendi!")
        return redirect("dashboard")

    context = {
        "form" : form
    }
    return render(request,"add_article.html",context)

@staff_member_required()
def update_article(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance=article)
    superarticles = Article.objects.filter(is_superarticle = 1)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        if len(superarticles)>=2 and article.is_superarticle:
            article.is_superarticle = 0
            article.save()
            messages.warning(request,"Makale Başarıyla Güncellendi. Fakat En Fazla 2 Tane Haftanın İçeriği Olabileceği İçin Haftanın İçeriklerine Eklenemedi.")
            return redirect("dashboard")

        article.save()
        messages.success(request,"Makale Başarıyla Güncellendi!")
        return redirect("dashboard")

    context = {
        "form" : form
    }
    return render(request,"update.html",context)

@staff_member_required()
def delete_article(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi!")
    return redirect("dashboard")

@login_required(login_url="user:login")
def add_comment(request,id):
    article = get_object_or_404(Article,id=id)
    if request.method == "POST":
        comment_author = request.user
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article
        newComment.save()
        messages.success(request,"Yorum Başarıyla Eklendi!")
    return redirect(reverse("article:detail",kwargs={"id":id}))



def siyaset_yazi(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"siyaset-yazılar.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Siyaset-Yazı")
    context = {
        "articles" : articles
    }
    return render(request,"siyaset-yazılar.html",context)

def siyaset_haber(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"siyaset-haberler.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Siyaset-Haber")
    context = {
        "articles" : articles
    }
    return render(request,"siyaset-haberler.html",context)

def spor_yazi(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"spor-yazılar.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Spor-Yazı")
    context = {
        "articles" : articles
    }
    return render(request,"spor-yazılar.html",context)

def spor_haber(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"spor-haberler.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Spor-Haber")
    context = {
        "articles" : articles
    }
    return render(request,"spor-haberler.html",context)
def muzik(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"müzik.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Müzik")
    context = {
        "articles" : articles
    }
    return render(request,"müzik.html",context)

def sinema(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"sinema.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Sinema")
    context = {
        "articles" : articles
    }
    return render(request,"sinema.html",context)

def edebiyat(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"edebiyat.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Edebiyat")
    context = {
        "articles" : articles
    }
    return render(request,"edebiyat.html",context)

def sahne(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"sahne_sanatları.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Sahne Sanatları")
    context = {
        "articles" : articles
    }
    return render(request,"sahne_sanatları.html",context)

def gorsel(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"görsel_sanatlar.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Görsel Sanatlar")
    context = {
        "articles" : articles
    }
    return render(request,"görsel_sanatlar.html",context)

def gezi(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"gezinotu.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Gezi Notu")
    context = {
        "articles" : articles
    }
    return render(request,"gezinotu.html",context)

def ceviri(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"çeviri.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Çeviri")
    context = {
        "articles" : articles
    }
    return render(request,"çeviri.html",context)

article/templates/add_article.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class = "container">
<h1>Add Article</h1>
<hr style = "background-color: white">
<div class="row">
  <div class="col-md-6 offset-md-3">
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy}}
        <br>
        

        <button type = "submit" class = "btn btn-dark">Makale Ekle</button>
    </form>
  </div> 
</div>
</div>

{% endblock body %}

article/templates/detail.html
{% extends "layout.html" %}
{%load static%}
{% block body %}
<div class = "container">
<article>
        <header class="mb-4">
            <h1 class="fw-bolder mb-1">{{article.title}}</h1>
            <div class="text-muted fst-italic mb-2">{{article.created_date}} tarihinde {{article.author}} tarafından yayınlandı.</div>
        </header>
        {% if article.article_image %}
            <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>    
        {% endif %}
        
        <section class="mb-5">
            {{ article.content|safe }}
        </section>
    </article>

 <section class="mb-5">
                        <h4>Yorumlar <i class="bi bi-chat-left-dots"></i></h4>
                        <hr style = "background-color: white"><br>
                        <div class="card">
                            <div class="card-body">
                                <form class="mb-4" method = "post" action = "{%url 'article:add_comment' article.id%}">
                                {% csrf_token %}
                                <textarea class="form-control" name = "comment_content" rows="3" placeholder="Yorum ekle sen de görüşünü belirt!"></textarea><br>
                                <button type = "submit" class = "btn btn-dark">Yorum Ekle</button>
                                </form>

                                {% if comments %}
                                {% for comment in comments %}
                                    <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="{%static 'png/cute-64x64.png' %}" alt="..." /><br></div>
                                    <div class="ms-3">
                                        <div class="fw-bold"><b>{{comment.comment_author}}</b></div>
                                        <small>{{comment.comment_date}} </small><br>
                                        {{comment.comment_content}}
                                    </div>
                                </div>
                                <br>
                                {% endfor %} 
                                {% else %}
                                <div class = "alert alert-warning">Henüz yorum yapılmamış. İlk yorum yapan siz olun.</div>
                                {% endif %}
                              
                            </div>
                            
                            </div>
                        </div>
                    </section>
                    
</div>
    
{% endblock body %}

article/templates/gezinotu.html
{% extends "layout.html" %}

{% block body %}
<div class = "container">
<h1>Gezi Notu</h1>
<hr style = "background-color: white">
<div class="container">
<form>
{% csrf_token %}
<input type="text" name = "keyword" class = "input-sm rounded" placeholder = "makale ara...">
<button type = "sumbit" class ="btn btn-secondary btn-sm">Ara</button>
</form>
<br>
  {% if articles %}
    <div class="row">
  {% for article in articles  %}
  <div class="col">
  <div class="card text-dark" style="width: 18rem;">
  {% if article.article_image %}
  <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
  {% endif %}
  
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text"><small class="text-muted">{{article.created_date}}</small></p>
    <p class="card-text">{{article.content|safe|truncatewords:30}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-secondary">Devamını Oku</a>
  </div>
</div>
<br>
  </div>
  {% endfor %}
  </div>
  {% else %}
  <div class = "alert alert-warning">Makale Bulunamadı!</div>
  {% endif %}
</div>
</div>

{% endblock body %}

article/templates/görsel_sanatlar.html
{% extends "layout.html" %}

{% block body %}
<div class = "container">
<h1>Görsel Sanatlar</h1>
<hr style = "background-color: white">
<div class="container">
<form>
{% csrf_token %}
<input type="text" name = "keyword" class = "input-sm rounded" placeholder = "makale ara...">
<button type = "sumbit" class ="btn btn-secondary btn-sm">Ara</button>
</form>
<br>
  {% if articles %}
    <div class="row">
  {% for article in articles  %}
  <div class="col">
  <div class="card text-dark" style="width: 18rem;">
  {% if article.article_image %}
  <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
  {% endif %}
  
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text"><small class="text-muted">{{article.created_date}}</small></p>
    <p class="card-text">{{article.content|safe|truncatewords:30}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-secondary">Devamını Oku</a>
  </div>
</div>
<br>
  </div>
  {% endfor %}
  </div>
  {% else %}
  <div class = "alert alert-warning">Makale Bulunamadı!</div>
  {% endif %}
</div>
</div>

{% endblock body %}

article/templates/layout.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Raleway:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="icon" href="{%static 'png/favicon.png'%}" sizes="32x32" type="image/png">
    <title>gazetekomun.com</title>
    
</head>
<body>
    {% include "includes/navbar.html" %}
    <hr>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == "info" %}
                <div  class="alert alert-danger">{{ message }}</div>
            {% else %}
                <div  class="alert alert-{{message.tags}}">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock body %}
    
    <br>
    <footer class="blog-footer ">
  <p>Bu sitenin tüm hakları saklıdır. <b><i>ysd®</i></b>  tarafından bu topluluk için yapılmıştır.</p>
  <p>
  </p>
</footer>


    
    



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

article/templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>Giriş Yap</h1>
    <hr style = "background-color: white">
    <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-dark">Giriş Yap</button>
    </form>
    <br>
    <p>Henüz hesabın yok mu ? <a href="{% url 'user:register' %}">buraya</a> tıklayarak kayıt olabilirsin.</p>
  </div> 
</div>


{% endblock body %}

article/templates/müzik.html
{% extends "layout.html" %}

{% block body %}
<div class = "container">
<h1>Müzik</h1>
<hr style = "background-color: white">
<div class="container">
<form>
{% csrf_token %}
<input type="text" name = "keyword" class = "input-sm rounded" placeholder = "makale ara...">
<button type = "sumbit" class ="btn btn-secondary btn-sm">Ara</button>
</form>
<br>
  {% if articles %}
    <div class="row">
  {% for article in articles  %}
  <div class="col">
  <div class="card text-dark" style="width: 18rem;">
  {% if article.article_image %}
  <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
  {% endif %}
  
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text"><small class="text-muted">{{article.created_date}}</small></p>
    <p class="card-text">{{article.content|safe|truncatewords:30}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-secondary">Devamını Oku</a>
</div>
<br>
  </div>
  {% endfor %}
  </div>
  {% else %}
  <div class = "alert alert-warning">Makale Bulunamadı!</div>
  {% endif %}
</div>
</div>

{% endblock body %}

article/templates/sahne_sanatları.html
{% extends "layout.html" %}

{% block body %}
<div class = "container">
<h1>Sahne Sanatları</h1>
<hr style = "background-color: white">
<div class="container">
<form>
{% csrf_token %}
<input type="text" name = "keyword" class = "input-sm rounded" placeholder = "makale ara...">
<button type = "sumbit" class ="btn btn-secondary btn-sm">Ara</button>
</form>
<br>
  {% if articles %}
    <div class="row">
  {% for article in articles  %}
  <div class="col">
  <div class="card text-dark" style="width: 18rem;">
  {% if article.article_image %}
  <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
  {% endif %}
  
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text"><small class="text-muted">{{article.created_date}}</small></p>
    <p class="card-text">{{article.content|safe|truncatewords:30}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-secondary">Devamını Oku</a>
</div>
<br>
  </div>
  {% endfor %}
  </div>
  {% else %}
  <div class = "alert alert-warning">Makale Bulunamadı!</div>
  {% endif %}
</div>
</div>

{% endblock body %}

article/templates/sinema.html
{% extends "layout.html" %}

{% block body %}
<div class = "container">
<h1>Sinema</h1>
<hr style = "background-color: white">
<div class="container">
<form>
{% csrf_token %}
<input type="text" name = "keyword" class = "input-sm rounded" placeholder = "makale ara...">
<button type = "sumbit" class ="btn btn-secondary btn-sm">Ara</button>
</form>
<br>
  {% if articles %}
    <div class="row">
  {% for article in articles  %}
  <div class="col">
  <div class="card text-dark" style="width: 18rem;">
  {% if article.article_image %}
  <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
  {% endif %}
  
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text"><small class="text-muted">{{article.created_date}}</small></p>
    <p class="card-text">{{article.content|safe|truncatewords:30}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-secondary">Devamını Oku</a>
  </div>
</div>
<br>
  </div>
  {% endfor %}
  </div>
  {% else %}
  <div class = "alert alert-warning">Makale Bulunamadı!</div>
  {% endif %}
</div>
</div>

{% endblock body %}

article/templates/siyaset-haberler.html
{% extends "layout.html" %}

{% block body %}
<div class = "container">
<h1>Siyasi Haberler</h1>
<hr style = "background-color: white">
<div class="container">
<form>
{% csrf_token %}
<input type="text" name = "keyword" class = "input-sm rounded" placeholder = "makale ara...">
<button type = "sumbit" class ="btn btn-secondary btn-sm">Ara</button>
</form>
<br>
  {% if articles %}
    <div class="row">
  {% for article in articles  %}
  <div class="col">
  <div class="card text-dark" style="width: 18rem;">
  {% if article.article_image %}
  <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
  {% endif %}
  
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text"><small class="text-muted">{{article.created_date}}</small></p>
    <p class="card-text">{{article.content|safe|truncatewords:30}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-secondary">Devamını Oku</a>
  </div>
</div>
<br>
  </div>
  {% endfor %}
  </div>
  {% else %}
  <div class = "alert alert-warning">Makale Bulunamadı!</div>
  {% endif %}
</div>
</div>

{% endblock body %}}

article/templates/spor-haberler.html
{% extends "layout.html" %}

{% block body %}
<div class = "container">
<h1>Spor Haberleri</h1>
<hr style = "background-color: white">
<div class="container">
<form>
{% csrf_token %}
<input type="text" name = "keyword" class = "input-sm rounded" placeholder = "makale ara...">
<button type = "sumbit" class ="btn btn-secondary btn-sm">Ara</button>
</form>
<br>
  {% if articles %}
    <div class="row">
  {% for article in articles  %}
  <div class="col">
  <div class="card text-dark" style="width: 18rem;">
  {% if article.article_image %}
  <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
  {% endif %}
  
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text"><small class="text-muted">{{article.created_date}}</small></p>
    <p class="card-text">{{article.content|safe|truncatewords:30}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-secondary">Devamını Oku</a>
  </div>
</div>
<br>
  </div>
  {% endfor %}
  </div>
  {% else %}
  <div class = "alert alert-warning">Makale Bulunamadı!</div>
  {% endif %}
</div>
</div>

{% endblock body %}

article/templates/spor-yazılar.html
{% extends "layout.html" %}

{% block body %}
<div class = "container">
<h1>Spor Yazıları</h1>
<hr style = "background-color: white">
<div class="container">
<form>
{% csrf_token %}
<input type="text" name = "keyword" class = "input-sm rounded" placeholder = "makale ara...">
<button type = "sumbit" class ="btn btn-secondary btn-sm">Ara</button>
</form>
<br>
  {% if articles %}
    <div class="row">
  {% for article in articles  %}
  <div class="col">
  <div class="card text-dark" style="width: 18rem;">
  {% if article.article_image %}
  <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
  {% endif %}
  
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text"><small class="text-muted">{{article.created_date}}</small></p>
    <p class="card-text">{{article.content|safe|truncatewords:30}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-secondary">Devamını Oku</a>
  </div>
</div>
<br>
  </div>
  {% endfor %}
  </div>
  {% else %}
  <div class = "alert alert-warning">Makale Bulunamadı!</div>
  {% endif %}
</div>
</div>

{% endblock body %}