article/urls.py
from django.contrib import admin
from django.urls import path

app_name = "article"


from .views import *
urlpatterns = [
    path('add_article/',add_article,name = "add_article"),
    path('detail/<int:id>/',detail,name="detail"),
    path('update/<int:id>/',update_article,name="update_article"),
    path('delete/<int:id>/',delete_article,name="delete_article"),
    path('add_comment/<int:id>/',add_comment,name="add_comment"),

]

myblog_2/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from article.views import dashboard
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('create_about/',views.create_about,name ="create_about"),
    path('about/',views.about,name ="about"),
    path('siyaset-yazi/',views.siyaset_yazi,name = "siyaset-yazi"),
    path('siyaset-haber/',views.siyaset_haber,name = "siyaset-haber"),
    path('articles/',include("article.urls")),
    path('user/',include('user.urls')),
    path('dashboard/',dashboard,name="dashboard"),
    path('spor-yazi/',views.spor_yazi,name = "spor-yazi"),
    path('spor-yazilar/',views.spor_haber,name = "spor_haber"),
    path('müzik/',views.muzik,name = "muzik"),
    path('sinema/',views.sinema,name = "sinema"),
    path('edebiyat/',views.edebiyat,name = "edebiyat"),
    path('sahne-sanatlari/',views.sahne,name = "sahne_sanatlari"),
    path('gorsel-sanatlar/',views.gorsel,name = "gorsel"),
    path('gezi-notu/',views.gezi,name = "gezi"),
    path('ceviri/',views.ceviri,name = "ceviri"),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.contrib.auth.models import Permission
from django.urls import path,include

app_name = "user"
Permission
from .views import *
urlpatterns = [
    path('register/',register,name="register"),
    path('login/',loginusr,name="login"),
    path('logout/',logoutusr,name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

ARTICLE_CATEGORY = (
    ("Siyaset-Yazı", "Siyaset-Yazı"),
    ("Siyaset-Haber", "Siyaset-Haber"),
    ("Spor-Yazı", "Spor-Yazı"),
    ("Spor-Haber", "Spor-Haber"),
    ("Müzik", "Müzik"),
    ("Sinema", "Sinema"),
    ("Edebiyat", "Edebiyat"),
    ("Sahne Sanatları", "Sahne Sanatları"),
    ("Görsel Sanatlar", "Görsel Sanatlar"),
    ("Gezi Notu", "Gezi Notu"),
    ("Çeviri", "Çeviri"),
)



class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete= models.CASCADE,verbose_name="Author")
    title = models.CharField(max_length= 50,verbose_name="Başlık")
    content = RichTextField(verbose_name = "İçerik")
    created_date = models.DateTimeField(auto_now_add= True,verbose_name="Creadet Date")
    article_image = models.FileField(blank=True,null=True,verbose_name="Makale Fotoğrafı")
    article_category = models.CharField(
        max_length=20,
        choices=ARTICLE_CATEGORY,
        default="Siyaset-Yazı",
        verbose_name="Makale Türü"
    )
    is_superarticle = models.BooleanField(verbose_name="Haftanın İçeriği Yap",default=0)
    def __str__(self):
     return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model): 
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="article" ,related_name="comments")
    comment_author = models.CharField(max_length= 50 ,verbose_name="c_author")
    comment_content = models.CharField(max_length=200,verbose_name="c_content")
    comment_date = models.DateTimeField(auto_now_add=True,verbose_name="comment_date")
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

class About(models.Model):
    author = models.ForeignKey("auth.User", on_delete= models.CASCADE,verbose_name="Author",default=None)
    content = RichTextField(verbose_name = "İçerik")

article/forms.py
from django import forms
from .models import About, Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image","article_category","is_superarticle"]

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = ["content"]

article/views.py
from django.db.models.query import RawQuerySet
from django.http import response
from django.shortcuts import redirect, render, HttpResponse,get_object_or_404
from django.urls import reverse
from .forms import ArticleForm, AboutForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import About, Article, Comment

# Create your views here.

def index(request):
    superarticles = Article.objects.filter(is_superarticle = 1)
    
    last_articles_query = Article.objects.all()
    last_articles = list()
    if len(last_articles_query)<6:
        for i in range(len(last_articles_query)):
            last_articles.append(last_articles_query[i])
    else:
        for i in range(6):
            last_articles.append(last_articles_query[i])

    return render(request,"index.html",{"s_articles":superarticles,"last_articles":last_articles})

def create_about(request):
    about = get_object_or_404(About)
    form = AboutForm(request.POST or None,instance=about)

    if form.is_valid():
        about_content = form.save(commit=False)
        about_content.author = request.user
        about_content.save()
        messages.success(request,"Hakkımızda Sayfası Başarıyla Güncellendi!")
        return redirect("dashboard")

    context = {
        "form" : form
    }
    return render(request,"create_about.html",context)

def about(request):
    abt = get_object_or_404(About,id=1)
    return render(request,"about.html",{"abt":abt})


def detail(request,id):
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    return render(request, "detail.html",{"article" : article, "comments" : comments})

@staff_member_required()
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles" : articles
    }
    return render(request,"dashboard.html",context)

@staff_member_required()
def add_article(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    superarticles = Article.objects.filter(is_superarticle = 1)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        if len(superarticles)>=2 and article.is_superarticle:
            article.is_superarticle = 0
            article.save()
            messages.warning(request,"Makale Başarıyla Eklendi. Fakat En Fazla 2 Tane Haftanın İçeriği Olabileceği İçin Haftanın İçeriklerine Eklenemedi.")
            return redirect("dashboard")

        article.save()
        messages.success(request,"Makale Başarıyla Eklendi!")
        return redirect("dashboard")

    context = {
        "form" : form
    }
    return render(request,"add_article.html",context)

@staff_member_required()
def update_article(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance=article)
    superarticles = Article.objects.filter(is_superarticle = 1)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        if len(superarticles)>=2 and article.is_superarticle:
            article.is_superarticle = 0
            article.save()
            messages.warning(request,"Makale Başarıyla Güncellendi. Fakat En Fazla 2 Tane Haftanın İçeriği Olabileceği İçin Haftanın İçeriklerine Eklenemedi.")
            return redirect("dashboard")

        article.save()
        messages.success(request,"Makale Başarıyla Güncellendi!")
        return redirect("dashboard")

    context = {
        "form" : form
    }
    return render(request,"update.html",context)

@staff_member_required()
def delete_article(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi!")
    return redirect("dashboard")

@login_required(login_url="user:login")
def add_comment(request,id):
    article = get_object_or_404(Article,id=id)
    if request.method == "POST":
        comment_author = request.user
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article
        newComment.save()
        messages.success(request,"Yorum Başarıyla Eklendi!")
    return redirect(reverse("article:detail",kwargs={"id":id}))



def siyaset_yazi(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"siyaset-yazılar.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Siyaset-Yazı")
    context = {
        "articles" : articles
    }
    return render(request,"siyaset-yazılar.html",context)

def siyaset_haber(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"siyaset-haberler.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Siyaset-Haber")
    context = {
        "articles" : articles
    }
    return render(request,"siyaset-haberler.html",context)

def spor_yazi(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"spor-yazılar.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Spor-Yazı")
    context = {
        "articles" : articles
    }
    return render(request,"spor-yazılar.html",context)

def spor_haber(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"spor-haberler.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Spor-Haber")
    context = {
        "articles" : articles
    }
    return render(request,"spor-haberler.html",context)
def muzik(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"müzik.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Müzik")
    context = {
        "articles" : articles
    }
    return render(request,"müzik.html",context)

def sinema(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"sinema.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Sinema")
    context = {
        "articles" : articles
    }
    return render(request,"sinema.html",context)

def edebiyat(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"edebiyat.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Edebiyat")
    context = {
        "articles" : articles
    }
    return render(request,"edebiyat.html",context)

def sahne(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"sahne_sanatları.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Sahne Sanatları")
    context = {
        "articles" : articles
    }
    return render(request,"sahne_sanatları.html",context)

def gorsel(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"görsel_sanatlar.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Görsel Sanatlar")
    context = {
        "articles" : articles
    }
    return render(request,"görsel_sanatlar.html",context)

def gezi(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"gezinotu.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Gezi Notu")
    context = {
        "articles" : articles
    }
    return render(request,"gezinotu.html",context)

def ceviri(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"çeviri.html",{"articles" : articles})
    articles = Article.objects.filter(article_category = "Çeviri")
    context = {
        "articles" : articles
    }
    return render(request,"çeviri.html",context)

article/templates/includes/navbar.html
{%load static%}
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
          <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a
             class="btn btn-link btn-floating btn-lg text-dark m-1"
             href="#!"
             role="button"
             data-mdb-ripple-color="dark"
             ><i class="bi bi-facebook"></i
            ></a>

          <!-- Twitter -->
          <a
             class="btn btn-link btn-floating btn-lg text-dark m-1"
             href="#!"
             role="button"
             data-mdb-ripple-color="dark"
             ><i class="bi bi-twitter"></i
            ></a>


          <!-- Instagram -->
          <a
             class="btn btn-link btn-floating btn-lg text-dark m-1"
             href="#!"
             role="button"
             data-mdb-ripple-color="dark"
             ><i class="bi bi-instagram"></i
            ></a>

    
       
        </section>
        <!-- Section: Social media -->
      </div>
      </div>
      <div class="col-4 text-center">
         <a class="blog-header-logo text-dark" href="/" style = "text-decoration:none"><img src="{%static 'png/logo_transparent.png'%}" style = "max-height:200px;"alt="..."></a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center" style = "margin-top:150px">
        {% if request.user.is_authenticated %}
         {% if request.user.username == "yusufs" %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'dashboard' %}">Admin Paneli</a>
        {% endif %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'user:logout' %}" style = "margin-left:5px">Çıkış Yap</a>
         {% else %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'user:login' %}" style = "margin-left:5px">Giriş Yap/Kayıt Ol</a>
        {% endif %}


      </div>
    </div>
  </header>

  <div class=" py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <div class="dropdown" style = "margin-top:10px">
  <a type="button" class="dropdown-toggle" data-bs-toggle="dropdown" style = "color:gray;text-decoration:none">
    Siyaset
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'siyaset-yazi' %}">Yazılar</a></li>
    <li><a class="dropdown-item" href="{% url 'siyaset-haber' %}">Haberler</a></li>
  </ul>
</div>
      
       <div class="dropdown " style = "margin-top:10px">
  <a type="button" class="dropdown-toggle" data-bs-toggle="dropdown" style = "color:gray;text-decoration:none">
    Spor
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'spor-yazi' %}">Yazılar</a></li>
    <li><a class="dropdown-item" href="{% url 'spor_haber' %}">Haberler</a></li>
  </ul>
</div>
      
      
       <div class="dropdown " style = "margin-top:10px">
  <a type="button" class="dropdown-toggle" data-bs-toggle="dropdown" style = "color:gray;text-decoration:none">
    Kültür-Sanat
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'muzik' %}">Müzik</a></li>
    <li><a class="dropdown-item" href="{% url 'sinema' %}">Sinema</a></li>
    <li><a class="dropdown-item" href="{% url 'edebiyat' %}">Edebiyat</a></li>
    <li><a class="dropdown-item" href="{% url 'sahne_sanatlari' %}">Sahne Sanatları</a></li>
    <li><a class="dropdown-item" href="{% url 'gorsel' %}">Görsel Sanatlar</a></li>
  </ul>
</div>
      <a class="p-2 link-secondary" href="{% url 'gezi' %}">Gezi Notu</a>
      <a class="p-2 link-secondary" href="{% url 'ceviri' %}">Çeviri</a>
  
    </nav>
  </div>
</div>

article/templates/includes/posttemplate.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Post - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on January 1, 2021 by Start Bootstrap</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                            <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                            <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                            <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                            <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                            <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                                <!-- Comment with nested comments-->
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                        <!-- Child comment 1-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                            </div>
                                        </div>
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Single comment-->
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>